// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYi2P6gv2_4TMyCqzMaydJyt52IPGGocU',
    appId: '1:327988665553:web:39f79b3f9fef7953c9f9f0',
    messagingSenderId: '327988665553',
    projectId: 'tesa-8ea4b',
    authDomain: 'tesa-8ea4b.firebaseapp.com',
    storageBucket: 'tesa-8ea4b.appspot.com',
    measurementId: 'G-D9YPX7S4YJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu68O1PtngCoUy9SxTyS5RFwf5PytIe28',
    appId: '1:327988665553:android:59027e40c8bd15dbc9f9f0',
    messagingSenderId: '327988665553',
    projectId: 'tesa-8ea4b',
    storageBucket: 'tesa-8ea4b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJj8m6B_vbmxdngV_nrr8ccITovc1CF98',
    appId: '1:327988665553:ios:e697cc9084ab0d67c9f9f0',
    messagingSenderId: '327988665553',
    projectId: 'tesa-8ea4b',
    storageBucket: 'tesa-8ea4b.appspot.com',
    iosBundleId: 'com.example.pingolearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJj8m6B_vbmxdngV_nrr8ccITovc1CF98',
    appId: '1:327988665553:ios:e697cc9084ab0d67c9f9f0',
    messagingSenderId: '327988665553',
    projectId: 'tesa-8ea4b',
    storageBucket: 'tesa-8ea4b.appspot.com',
    iosBundleId: 'com.example.pingolearn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYi2P6gv2_4TMyCqzMaydJyt52IPGGocU',
    appId: '1:327988665553:web:e3c46e541efee871c9f9f0',
    messagingSenderId: '327988665553',
    projectId: 'tesa-8ea4b',
    authDomain: 'tesa-8ea4b.firebaseapp.com',
    storageBucket: 'tesa-8ea4b.appspot.com',
    measurementId: 'G-1XSQ75PRQJ',
  );
}
